export const mockDetailedSession = {
  id: 'sess123',
  filename: '2026_05_28_P1.xml',
  filePath: 'C:\\LMU\\UserData\\LOG\\Results\\2026_05_28_P1.xml',
  trackVenue: 'Spa',
  trackCourse: 'GP',
  timeString: '2026/05/28 14:00',
  sessionType: 'Practice',
  sessionName: 'P1',
  eventTimeString: '14:00:00',
  eventName: 'Test Event',
  ambientTemp: '24°C',
  trackTemp: '32°C',
  weatherCondition: '☀️ Dry',
  timeOfDayCategory: 'Daytime',
  isNight: false,
  isWet: false,
  driversCount: 2,
  weather: {
    condition: 'Dry' as const,
    timeOfDay: 'Daytime' as const,
    weatherString: '☀️ Dry • Daytime',
  },
  settings: {
    modeSetting: 'Race Weekend',
    damageMultiplier: 50,
    fuelMultiplier: 1,
    tireMultiplier: 1,
    tireWarmers: true,
    fixedSetups: false,
    durationMinutes: 60,
  },
  matchingReplayFile: {
    name: 'spa_replay.vcr',
    path: 'C:\\LMU\\UserData\\Replays\\spa_replay.vcr',
    sizeFormatted: '4.2 MB',
    createdDateFormatted: '2026/05/28 14:30',
  },
  playerDriver: {
    name: 'Sim Driver',
    carType: 'Ferrari 499P',
    carClass: 'LMH',
    carNumber: '50',
    teamName: 'AF Corse',
    isPlayer: true,
    position: 1,
    classPosition: 1,
    bestLapTime: 122.0,
    bestLapTimeString: '2:02.000',
    bestS1: 34.0,
    bestS2: 42.0,
    bestS3: 46.0,
    theoreticalBest: 122.0,
    theoreticalBestString: '2:02.000',
    bestLapPaceCategory: 'Alien' as const,
    bestLapPacePercentage: 100.1,
    avgFuelPerLap: 2.5,
    estFuelStintLaps: 40,
    avgVePerLap: 3.8,
    estVeStintLaps: 26,
    lapsCount: 3,
    laps: [
      {
        lapNum: 1,
        position: 1,
        lapTime: 123.0,
        lapTimeString: '2:03.000',
        s1: 35.0,
        s2: 42.0,
        s3: 46.0,
        topSpeed: 320.0,
        fCompound: 'Hard',
        rCompound: 'Hard',
        tireWear: { fl: 98.0, fr: 98.0, rl: 97.5, rr: 97.5, avg: 97.8 },
        fuel: 97.5,
        fuelUsed: 2.5,
        virtualEnergy: 96.2,
        virtualEnergyUsed: 3.8,
        elapsedSeconds: 123.0,
        elapsedTimeString: '2:03.0',
        isPitStop: false,
        isValid: true,
        paceCategory: 'Good' as const,
        pacePercentage: 102.0,
      },
      {
        lapNum: 2,
        position: 1,
        lapTime: 122.0,
        lapTimeString: '2:02.000',
        s1: 34.0,
        s2: 42.0,
        s3: 46.0,
        topSpeed: 322.0,
        fCompound: 'Hard',
        rCompound: 'Hard',
        tireWear: { fl: 95.0, fr: 94.5, rl: 94.0, rr: 94.0, avg: 94.4 },
        fuel: 95.0,
        fuelUsed: 2.5,
        virtualEnergy: 92.4,
        virtualEnergyUsed: 3.8,
        elapsedSeconds: 245.0,
        elapsedTimeString: '4:05.0',
        isPitStop: false,
        isValid: true,
        paceCategory: 'Competitive' as const,
        pacePercentage: 101.0,
      },
      {
        lapNum: 3,
        position: 1,
        lapTime: 135.0,
        lapTimeString: '2:15.000',
        s1: 36.0,
        s2: 45.0,
        s3: 54.0,
        topSpeed: 290.0,
        fCompound: 'Hard',
        rCompound: 'Hard',
        tireWear: { fl: 92.0, fr: 91.0, rl: 90.5, rr: 90.5, avg: 91.0 },
        fuel: 92.5,
        fuelUsed: 2.5,
        virtualEnergy: 88.6,
        virtualEnergyUsed: 3.8,
        elapsedSeconds: 380.0,
        elapsedTimeString: '6:20.0',
        pitStopDuration: 13.0,
        pitStopDurationString: '+13.0s',
        isPitStop: true,
        isValid: false,
        paceCategory: 'Offline' as const,
        pacePercentage: 112.5,
      },
    ],
  },
  drivers: [
    {
      name: 'Sim Driver',
      carType: 'Ferrari 499P',
      carClass: 'LMH',
      carNumber: '50',
      teamName: 'AF Corse',
      isPlayer: true,
      position: 1,
      classPosition: 1,
      bestLapTime: 122.0,
      bestLapTimeString: '2:02.000',
      bestS1: 34.0,
      bestS2: 42.0,
      bestS3: 46.0,
      theoreticalBest: 122.0,
      theoreticalBestString: '2:02.000',
      avgFuelPerLap: 2.5,
      estFuelStintLaps: 40,
      avgVePerLap: 3.8,
      estVeStintLaps: 26,
      lapsCount: 3,
      laps: [
        {
          lapNum: 1,
          position: 1,
          lapTime: 123.0,
          lapTimeString: '2:03.000',
          s1: 35.0,
          s2: 42.0,
          s3: 46.0,
          topSpeed: 320.0,
          fCompound: 'Hard',
          rCompound: 'Hard',
          tireWear: { fl: 98.0, fr: 98.0, rl: 97.5, rr: 97.5, avg: 97.8 },
          fuel: 97.5,
          fuelUsed: 2.5,
          virtualEnergy: 96.2,
          virtualEnergyUsed: 3.8,
          elapsedSeconds: 123.0,
          elapsedTimeString: '2:03.0',
          isPitStop: false,
          isValid: true,
          paceCategory: 'Good' as const,
          pacePercentage: 102.0,
        },
        {
          lapNum: 2,
          position: 1,
          lapTime: 122.0,
          lapTimeString: '2:02.000',
          s1: 34.0,
          s2: 42.0,
          s3: 46.0,
          topSpeed: 322.0,
          fCompound: 'Hard',
          rCompound: 'Hard',
          tireWear: { fl: 95.0, fr: 94.5, rl: 94.0, rr: 94.0, avg: 94.4 },
          fuel: 95.0,
          fuelUsed: 2.5,
          virtualEnergy: 92.4,
          virtualEnergyUsed: 3.8,
          elapsedSeconds: 245.0,
          elapsedTimeString: '4:05.0',
          isPitStop: false,
          isValid: true,
          paceCategory: 'Competitive' as const,
          pacePercentage: 101.0,
        },
        {
          lapNum: 3,
          position: 1,
          lapTime: 135.0,
          lapTimeString: '2:15.000',
          s1: 36.0,
          s2: 45.0,
          s3: 54.0,
          topSpeed: 290.0,
          fCompound: 'Hard',
          rCompound: 'Hard',
          tireWear: { fl: 92.0, fr: 91.0, rl: 90.5, rr: 90.5, avg: 91.0 },
          fuel: 92.5,
          fuelUsed: 2.5,
          virtualEnergy: 88.6,
          virtualEnergyUsed: 3.8,
          elapsedSeconds: 380.0,
          elapsedTimeString: '6:20.0',
          pitStopDuration: 13.0,
          pitStopDurationString: '+13.0s',
          isPitStop: true,
          isValid: false,
          paceCategory: 'Offline' as const,
          pacePercentage: 112.5,
        },
      ],
    },
    {
      name: 'AI Driver 2',
      carType: 'Porsche 963',
      carClass: 'LMH',
      carNumber: '5',
      teamName: 'Penske',
      isPlayer: false,
      position: 2,
      classPosition: 2,
      bestLapTime: 124.0,
      bestLapTimeString: '2:04.000',
      bestS1: 35.0,
      bestS2: 43.0,
      bestS3: 46.0,
      theoreticalBest: 124.0,
      theoreticalBestString: '2:04.000',
      lapsCount: 1,
      laps: [
        {
          lapNum: 1,
          position: 2,
          lapTime: 124.0,
          lapTimeString: '2:04.000',
          s1: 35.0,
          s2: 43.0,
          s3: 46.0,
          topSpeed: 318.0,
          fCompound: 'Medium',
          rCompound: 'Medium',
          isPitStop: false,
          isValid: true,
          paceCategory: 'Good' as const,
          pacePercentage: 102.8,
        },
      ],
    },
  ],
};
