import { resolveTrackLayoutKey } from './trackLayout.js';

export interface CircuitSpecification {
  layoutKey: string;
  officialName: string;
  layoutName: string;
  country: string;
  countryCode: string;
  flagEmoji: string;
  city: string;
  officialLengthMeters: number;
  officialLengthKm: number;
  officialLengthMiles: number;
  turnCount: number;
  direction: 'Clockwise' | 'Counter-Clockwise';
  elevationChangeMeters?: number;
  famousCorners: string[];
  boundarySource: 'TUM-survey' | 'Track-Atlas' | 'OpenStreetMap' | 'Hybrid' | 'Telemetry-Corridor';
  boundarySourceDescription: string;
  parsedFrom: string;
  fiaGrade?: string;
  openedYear?: number;
}

export const CIRCUIT_SPECIFICATIONS: Record<string, CircuitSpecification> = {
  monza_gp: {
    layoutKey: 'monza_gp',
    officialName: 'Autodromo Nazionale Monza',
    layoutName: 'Grand Prix Circuit',
    country: 'Italy',
    countryCode: 'IT',
    flagEmoji: '🇮🇹',
    city: 'Monza, Lombardy',
    officialLengthMeters: 5793,
    officialLengthKm: 5.793,
    officialLengthMiles: 3.600,
    turnCount: 11,
    direction: 'Clockwise',
    elevationChangeMeters: 13,
    famousCorners: ['Variante del Rettifilo (T1-T2)', 'Curva Grande (T3)', 'Variante della Roggia (T4-T5)', 'Curve di Lesmo (T6-T7)', 'Variante Ascari (T8-T10)', 'Curva Parabolica / Alboreto (T11)'],
    boundarySource: 'TUM-survey',
    boundarySourceDescription: 'Centimeter-accurate lidar survey from Technical University of Munich (TUM) Racetrack Database aligned to LMU replay telemetry with 0.04% scale precision.',
    parsedFrom: 'LMU Results XML (TrackVenue="Autodromo Nazionale Monza", TrackCourse="Autodromo Nazionale Monza") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1922,
  },
  monza_curvagrande: {
    layoutKey: 'monza_curvagrande',
    officialName: 'Autodromo Nazionale Monza',
    layoutName: 'Curva Grande Circuit',
    country: 'Italy',
    countryCode: 'IT',
    flagEmoji: '🇮🇹',
    city: 'Monza, Lombardy',
    officialLengthMeters: 5766,
    officialLengthKm: 5.766,
    officialLengthMiles: 3.583,
    turnCount: 9,
    direction: 'Clockwise',
    elevationChangeMeters: 13,
    famousCorners: ['Direct Straight to Curva Grande (Bypasses Rettifilo)', 'Variante della Roggia', 'Lesmo 1 & 2', 'Variante Ascari', 'Curva Parabolica'],
    boundarySource: 'Hybrid',
    boundarySourceDescription: 'Hybrid boundary synthesis (94.6% anchored to TUM survey + 160m telemetry connector bypassing the Rettifilo chicane).',
    parsedFrom: 'LMU Results XML (TrackVenue="Autodromo Nazionale Monza", TrackCourse="Monza Curva Grande Circuit") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1922,
  },
  spa_gp: {
    layoutKey: 'spa_gp',
    officialName: 'Circuit de Spa-Francorchamps',
    layoutName: 'Grand Prix Circuit',
    country: 'Belgium',
    countryCode: 'BE',
    flagEmoji: '🇧🇪',
    city: 'Stavelot / Francorchamps, Ardennes',
    officialLengthMeters: 7004,
    officialLengthKm: 7.004,
    officialLengthMiles: 4.352,
    turnCount: 19,
    direction: 'Clockwise',
    elevationChangeMeters: 102,
    famousCorners: ['La Source Hairpin (T1)', 'Eau Rouge & Raidillon (T2-T4)', 'Kemmel Straight', 'Les Combes (T5-T7)', 'Bruxelles / Rivage (T8)', 'Pouhon / Double Gauche (T10-T11)', 'Fagnes / Pif-Paf (T12-T13)', 'Blanchimont (T16-T17)', 'Bus Stop Chicane (T18-T19)'],
    boundarySource: 'TUM-survey',
    boundarySourceDescription: 'Centimeter-accurate lidar survey from Technical University of Munich (TUM) Racetrack Database with exact 1:1 metric modeling.',
    parsedFrom: 'LMU Results XML (TrackVenue="Circuit de Spa-Francorchamps", TrackCourse="Circuit de Spa-Francorchamps") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1921,
  },
  sarthe_full: {
    layoutKey: 'sarthe_full',
    officialName: 'Circuit des 24 Heures du Mans',
    layoutName: 'Full 24 Hours Circuit (Circuit de la Sarthe)',
    country: 'France',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    city: 'Le Mans, Sarthe',
    officialLengthMeters: 13626,
    officialLengthKm: 13.626,
    officialLengthMiles: 8.467,
    turnCount: 33,
    direction: 'Clockwise',
    elevationChangeMeters: 37,
    famousCorners: ['Dunlop Chicane & Passerelle (T1-T3)', 'Esses de la Forêt & Tertre Rouge (T4-T6)', 'Ligne Droite des Hunaudières (Mulsanne Straight)', 'Chicanes Forza & Michelin (T7-T12)', 'Mulsanne Corner (T13)', 'Indianapolis (T14-T15)', 'Arnage (T16)', 'Porsche Curves (T17-T23)', 'Maison Blanche & Ford Chicanes (T27-T33)'],
    boundarySource: 'Track-Atlas',
    boundarySourceDescription: 'Curvature-adaptive centerline derived from Track-Atlas GPS survey, resampled at 2.5m step intervals with FIA/ACO 12-15m road width model.',
    parsedFrom: 'LMU Results XML (TrackVenue="Circuit de la Sarthe", TrackCourse="Circuit de la Sarthe") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 2 / ACO Homologated',
    openedYear: 1923,
  },
  cota_gp: {
    layoutKey: 'cota_gp',
    officialName: 'Circuit of the Americas (COTA)',
    layoutName: 'Grand Prix Circuit',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Austin, Texas',
    officialLengthMeters: 5513,
    officialLengthKm: 5.513,
    officialLengthMiles: 3.426,
    turnCount: 20,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 41,
    famousCorners: ['133-ft Elevation Uphill Blind Apex (T1)', 'Maggotts/Becketts-style Esses (T2-T6)', 'Blind Sweeper (T10)', 'Hairpin (T11)', 'Multi-apex Carousel (T16-T18)'],
    boundarySource: 'TUM-survey',
    boundarySourceDescription: 'Centimeter-accurate lidar survey from Technical University of Munich (TUM) Racetrack Database aligned to LMU replay telemetry.',
    parsedFrom: 'LMU Results XML (TrackVenue="Circuit of the Americas", TrackCourse="Circuit of the Americas") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 2012,
  },
  barcelona_gp: {
    layoutKey: 'barcelona_gp',
    officialName: 'Circuit de Barcelona-Catalunya',
    layoutName: 'Grand Prix Circuit (Modern Layout)',
    country: 'Spain',
    countryCode: 'ES',
    flagEmoji: '🇪🇸',
    city: 'Montmeló, Catalonia',
    officialLengthMeters: 4657,
    officialLengthKm: 4.657,
    officialLengthMiles: 2.894,
    turnCount: 14,
    direction: 'Clockwise',
    elevationChangeMeters: 30,
    famousCorners: ['Elf Chicane (T1-T2)', 'Curva Renault (T3)', 'Repsol (T4)', 'Seat Hairpin (T5)', 'Campsa (T9)', 'La Caixa Hairpin (T10)', 'Fast Sweeping Final Turns (T13-T14)'],
    boundarySource: 'TUM-survey',
    boundarySourceDescription: 'Centimeter-accurate lidar survey from Technical University of Munich (TUM) Racetrack Database with high-speed chicane removal.',
    parsedFrom: 'LMU Results XML (TrackVenue="Circuit de Barcelona", TrackCourse="Circuit de Barcelona") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1991,
  },
  interlagos_gp: {
    layoutKey: 'interlagos_gp',
    officialName: 'Autódromo José Carlos Pace (Interlagos)',
    layoutName: 'Grand Prix Circuit',
    country: 'Brazil',
    countryCode: 'BR',
    flagEmoji: '🇧🇷',
    city: 'São Paulo',
    officialLengthMeters: 4309,
    officialLengthKm: 4.309,
    officialLengthMiles: 2.677,
    turnCount: 15,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 40,
    famousCorners: ['Senna ‘S’ (T1-T2)', 'Curva do Sol (T3)', 'Descida do Lago (T4-T5)', 'Ferradura (T6-T7)', 'Laranjinha (T8)', 'Bico de Pato (T10)', 'Mergulho (T11)', 'Junção (T12)', 'Subida dos Boxes (T13-T15)'],
    boundarySource: 'TUM-survey',
    boundarySourceDescription: 'Centimeter-accurate lidar survey from Technical University of Munich (TUM) Racetrack Database aligned to LMU replay telemetry.',
    parsedFrom: 'LMU Results XML (TrackVenue="Autódromo José Carlos Pace", TrackCourse="Autódromo José Carlos Pace") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1940,
  },
  silverstone_wec: {
    layoutKey: 'silverstone_wec',
    officialName: 'Silverstone Circuit',
    layoutName: 'Grand Prix Circuit - WEC',
    country: 'United Kingdom',
    countryCode: 'GB',
    flagEmoji: '🇬🇧',
    city: 'Northamptonshire / Buckinghamshire',
    officialLengthMeters: 5891,
    officialLengthKm: 5.891,
    officialLengthMiles: 3.660,
    turnCount: 18,
    direction: 'Clockwise',
    elevationChangeMeters: 11,
    famousCorners: ['Abbey (T1)', 'Farm (T2)', 'Village & The Loop (T3-T4)', 'Brooklands (T6)', 'Luffield & Woodcote (T7-T8)', 'Copse (T9)', 'Maggotts, Becketts & Chapel (T10-T14)', 'Hangar Straight', 'Stowe (T15)', 'Vale & Club (T16-T18)'],
    boundarySource: 'TUM-survey',
    boundarySourceDescription: 'Centimeter-accurate lidar survey from Technical University of Munich (TUM) Racetrack Database with high-frequency kerb geometry.',
    parsedFrom: 'LMU Results XML (TrackVenue="Silverstone Circuit", TrackCourse="Silverstone Grand Prix Circuit - WEC") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1948,
  },
  bahrain_wec: {
    layoutKey: 'bahrain_wec',
    officialName: 'Bahrain International Circuit',
    layoutName: 'Grand Prix Circuit (WEC 8 Hours)',
    country: 'Bahrain',
    countryCode: 'BH',
    flagEmoji: '🇧🇭',
    city: 'Sakhir, Southern Governorate',
    officialLengthMeters: 5412,
    officialLengthKm: 5.412,
    officialLengthMiles: 3.363,
    turnCount: 15,
    direction: 'Clockwise',
    elevationChangeMeters: 18,
    famousCorners: ['Michael Schumacher Turn (T1-T3)', 'Oasis Turn (T4)', 'High-speed Esses (T5-T7)', 'Downhill Off-camber Hairpin (T8-T10)', 'Double Apex (T14-T15)'],
    boundarySource: 'TUM-survey',
    boundarySourceDescription: 'Centimeter-accurate lidar survey from Technical University of Munich (TUM) Racetrack Database aligned to LMU replay telemetry.',
    parsedFrom: 'LMU Results XML (TrackVenue="Bahrain International Circuit", TrackCourse="Bahrain International Circuit") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  bahrain_outer: {
    layoutKey: 'bahrain_outer',
    officialName: 'Bahrain International Circuit',
    layoutName: 'Outer Circuit',
    country: 'Bahrain',
    countryCode: 'BH',
    flagEmoji: '🇧🇭',
    city: 'Sakhir, Southern Governorate',
    officialLengthMeters: 3543,
    officialLengthKm: 3.543,
    officialLengthMiles: 2.201,
    turnCount: 11,
    direction: 'Clockwise',
    elevationChangeMeters: 18,
    famousCorners: ['T1-T3 Complex', 'Outer Link High-speed Sweepers (T4-T8)', 'Double Apex Final Turns (T10-T11)'],
    boundarySource: 'Hybrid',
    boundarySourceDescription: 'Hybrid boundary synthesis (69.7% anchored to Bahrain WEC TUM survey + outer link connector matching official 3,543m FIA homologation length).',
    parsedFrom: 'LMU Results XML (TrackVenue="Bahrain International Circuit", TrackCourse="Bahrain Outer Circuit") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  bahrain_paddock: {
    layoutKey: 'bahrain_paddock',
    officialName: 'Bahrain International Circuit',
    layoutName: 'Paddock Circuit',
    country: 'Bahrain',
    countryCode: 'BH',
    flagEmoji: '🇧🇭',
    city: 'Sakhir, Southern Governorate',
    officialLengthMeters: 3888,
    officialLengthKm: 3.888,
    officialLengthMiles: 2.416,
    turnCount: 10,
    direction: 'Clockwise',
    elevationChangeMeters: 18,
    famousCorners: ['Paddock Straight Bypass', 'Inner Infield Complex', 'Technical Hairpin Sections'],
    boundarySource: 'Hybrid',
    boundarySourceDescription: 'Hybrid boundary synthesis (67.2% anchored to Bahrain WEC TUM survey + inner paddock link connector).',
    parsedFrom: 'LMU Results XML (TrackVenue="Bahrain International Circuit", TrackCourse="Bahrain Paddock Circuit") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  imola_gp: {
    layoutKey: 'imola_gp',
    officialName: 'Autodromo Internazionale Enzo e Dino Ferrari',
    layoutName: 'Grand Prix Circuit (Imola)',
    country: 'Italy',
    countryCode: 'IT',
    flagEmoji: '🇮🇹',
    city: 'Imola, Emilia-Romagna',
    officialLengthMeters: 4909,
    officialLengthKm: 4.909,
    officialLengthMiles: 3.050,
    turnCount: 19,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 34,
    famousCorners: ['Variante Tamburello (T2-T4)', 'Variante Villeneuve (T5-T6)', 'Tosa Hairpin (T7)', 'Piratella (T9)', 'Acque Minerali (T11-T13)', 'Variante Alta (T14-T15)', 'Rivazza 1 & 2 (T17-T18)'],
    boundarySource: 'Track-Atlas',
    boundarySourceDescription: 'Curvature-adaptive centerline derived from Track-Atlas GPS survey, resampled at 2.5m step intervals with FIA homologated 12.5m road width.',
    parsedFrom: 'LMU Results XML (TrackVenue="Autodromo Enzo e Dino Ferrari", TrackCourse="Autodromo Enzo e Dino Ferrari") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1953,
  },
  daytona_road_course: {
    layoutKey: 'daytona_road_course',
    officialName: 'Daytona International Speedway',
    layoutName: 'Road Course (with Le Mans Chicane)',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Daytona Beach, Florida',
    officialLengthMeters: 5729,
    officialLengthKm: 5.729,
    officialLengthMiles: 3.560,
    turnCount: 12,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 9,
    famousCorners: ['Infield Horseshoe (T1)', 'International Horseshoe (T3)', 'Kink (T4)', 'West Hairpin (T5-T6)', '31° High-banked Oval Turns (T7 & T12)', 'Backstretch Le Mans "Bus Stop" Chicane (T8-T11)'],
    boundarySource: 'OpenStreetMap',
    boundarySourceDescription: 'OpenStreetMap high-resolution geometry (OSM Relation 5254136 with Le Mans Chicane) aligned to LMU replay telemetry via Procrustes similarity.',
    parsedFrom: 'LMU Results XML (TrackVenue="Daytona International Speedway", TrackCourse="Daytona International Speedway Road Course") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 2 / IMSA Homologated',
    openedYear: 1959,
  },
  fuji_chicane: {
    layoutKey: 'fuji_chicane',
    officialName: 'Fuji Speedway',
    layoutName: 'Grand Prix Circuit (with Dunlop Chicane)',
    country: 'Japan',
    countryCode: 'JP',
    flagEmoji: '🇯🇵',
    city: 'Oyama, Shizuoka Prefecture',
    officialLengthMeters: 4563,
    officialLengthKm: 4.563,
    officialLengthMiles: 2.835,
    turnCount: 16,
    direction: 'Clockwise',
    elevationChangeMeters: 40,
    famousCorners: ['1.475 km Main Straight', 'T1 Daiichi (First Corner Hairpin)', 'Coca-Cola Corner (T3)', '100R (T4-T5)', 'Hairpin Corner (T6)', 'Dunlop Chicane (T10-T12)', '13th Corner', 'GR Supra / Netz Corner (T15)', 'Panasonic Corner (T16)'],
    boundarySource: 'Track-Atlas',
    boundarySourceDescription: 'Curvature-adaptive centerline derived from Track-Atlas GPS survey with 15m road width and Procrustes alignment to LMU telemetry.',
    parsedFrom: 'LMU Results XML (TrackVenue="Fuji Speedway", TrackCourse="Fuji Speedway") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1965,
  },
  fuji_classic: {
    layoutKey: 'fuji_classic',
    officialName: 'Fuji Speedway',
    layoutName: 'Classic Circuit (without Dunlop Chicane)',
    country: 'Japan',
    countryCode: 'JP',
    flagEmoji: '🇯🇵',
    city: 'Oyama, Shizuoka Prefecture',
    officialLengthMeters: 4514,
    officialLengthKm: 4.514,
    officialLengthMiles: 2.805,
    turnCount: 15,
    direction: 'Clockwise',
    elevationChangeMeters: 40,
    famousCorners: ['Main Straight', 'First Corner', '100R', 'Hairpin', 'Dunlop Bypass Straight', '13th Corner', 'Netz Corner', 'Panasonic Corner'],
    boundarySource: 'Hybrid',
    boundarySourceDescription: 'Hybrid boundary synthesis (97.7% anchored to Fuji GP Track-Atlas survey + 100m straight bypass removing the Dunlop chicane).',
    parsedFrom: 'LMU Results XML (TrackVenue="Fuji Speedway", TrackCourse="Fuji Speedway Classic") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1965,
  },
  portimao_wec: {
    layoutKey: 'portimao_wec',
    officialName: 'Autódromo Internacional do Algarve (Portimão)',
    layoutName: 'Grand Prix Circuit - WEC',
    country: 'Portugal',
    countryCode: 'PT',
    flagEmoji: '🇵🇹',
    city: 'Portimão, Algarve',
    officialLengthMeters: 4653,
    officialLengthKm: 4.653,
    officialLengthMiles: 2.891,
    turnCount: 15,
    direction: 'Clockwise',
    elevationChangeMeters: 30,
    famousCorners: ['Primeira (T1)', 'Lagos (T3)', 'Hairpin (T5)', 'Portimão Blind Crest (T8)', 'Craig Jones (T9)', 'Torre VIP Hairpin (T10-T11)', 'Galp (T14)', 'Curvão Blind Downhill Rollercoaster Drop (T15)'],
    boundarySource: 'OpenStreetMap',
    boundarySourceDescription: 'OpenStreetMap high-resolution geometry (OSM Relation 7509968) resampled at 2.5m intervals and aligned to LMU replay telemetry.',
    parsedFrom: 'LMU Results XML (TrackVenue="Algarve International Circuit", TrackCourse="Algarve International Circuit") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 2008,
  },
  sebring_full: {
    layoutKey: 'sebring_full',
    officialName: 'Sebring International Raceway',
    layoutName: 'Full 12-Hour Circuit',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Sebring, Florida',
    officialLengthMeters: 6019,
    officialLengthKm: 6.019,
    officialLengthMiles: 3.740,
    turnCount: 17,
    direction: 'Clockwise',
    elevationChangeMeters: 3,
    famousCorners: ['Rough Concrete Bumps Turn 1 (T1)', 'Apex Hairpin (T3)', 'Hairpin (T7)', 'Fangio Bends (T8)', 'Cunningham (T10)', 'Collier (T11)', 'Tower Turn (T13)', 'Le Mans / Ulmann Straight', 'Sunset Bend Bumpy Concrete Carousel (T17)'],
    boundarySource: 'Track-Atlas',
    boundarySourceDescription: 'Curvature-adaptive centerline derived from Track-Atlas GPS survey with FIA/IMSA 12-14m road width model.',
    parsedFrom: 'LMU Results XML (TrackVenue="Sebring International Raceway", TrackCourse="Sebring International Raceway") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 2 / IMSA Homologated',
    openedYear: 1950,
  },
  sebring_school: {
    layoutKey: 'sebring_school',
    officialName: 'Sebring International Raceway',
    layoutName: 'School Circuit (Short Layout)',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Sebring, Florida',
    officialLengthMeters: 3081,
    officialLengthKm: 3.081,
    officialLengthMiles: 1.914,
    turnCount: 10,
    direction: 'Clockwise',
    elevationChangeMeters: 3,
    famousCorners: ['Turn 1 Concrete', 'Hairpin Section', 'Runway Paddock Connector', 'Sunset Bend'],
    boundarySource: 'Hybrid',
    boundarySourceDescription: 'Hybrid boundary synthesis (97.1% anchored to Sebring Full Track-Atlas survey + runway paddock shortcut connector).',
    parsedFrom: 'LMU Results XML (TrackVenue="Sebring International Raceway", TrackCourse="Sebring School Circuit") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 2',
    openedYear: 1950,
  },
  laguna_seca: {
    layoutKey: 'laguna_seca',
    officialName: 'WeatherTech Raceway Laguna Seca',
    layoutName: 'Grand Prix Circuit',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Monterey County, California',
    officialLengthMeters: 3602,
    officialLengthKm: 3.602,
    officialLengthMiles: 2.238,
    turnCount: 11,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 55,
    famousCorners: ['Andretti Hairpin (T2)', 'Rahal Straight', 'The Corkscrew 5.5-story Blind Plunge (T8-T8A)', 'Rainey Curve (T9)', 'Final Hairpin (T11)'],
    boundarySource: 'Track-Atlas',
    boundarySourceDescription: 'Curvature-adaptive centerline derived from Track-Atlas GPS survey, resampled at 2.5m step intervals with Procrustes similarity alignment.',
    parsedFrom: 'LMU Results XML (TrackVenue="WeatherTech Raceway Laguna Seca", TrackCourse="WeatherTech Raceway Laguna Seca") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 2 / IMSA Homologated',
    openedYear: 1957,
  },
  qatar_short: {
    layoutKey: 'qatar_short',
    officialName: 'Lusail International Circuit',
    layoutName: 'Short Circuit',
    country: 'Qatar',
    countryCode: 'QA',
    flagEmoji: '🇶🇦',
    city: 'Lusail, Al Daayen',
    officialLengthMeters: 3661,
    officialLengthKm: 3.661,
    officialLengthMiles: 2.275,
    turnCount: 10,
    direction: 'Clockwise',
    elevationChangeMeters: 12,
    famousCorners: ['Main Straight', 'Turn 1 Hairpin', 'Inner Short Infield Link', 'High-speed Final Complex'],
    boundarySource: 'Telemetry-Corridor',
    boundarySourceDescription: 'Native telemetry limit corridor synthesized directly from multi-car high-frequency LMU binary replay telemetry.',
    parsedFrom: 'LMU Results XML (TrackVenue="Lusail International Circuit", TrackCourse="Lusail Short Circuit") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  paul_ricard_1a_v2_short: {
    layoutKey: 'paul_ricard_1a_v2_short',
    officialName: 'Circuit Paul Ricard',
    layoutName: '1A-V2 Short Circuit',
    country: 'France',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    city: 'Le Castellet, Var',
    officialLengthMeters: 5193,
    officialLengthKm: 5.193,
    officialLengthMiles: 3.227,
    turnCount: 14,
    direction: 'Clockwise',
    elevationChangeMeters: 8,
    famousCorners: ['S de la Verrerie (T1-T2)', 'Sainte-Baume (T3-T5)', 'Ligne Droite du Mistral with Chicane (T6-T9)', 'Courbe de Signes 290+ km/h Flat-out Sweeper (T10)', 'Double Droite du Beausset (T11-T12)', 'Bendor (T13)', 'Pont (T14)'],
    boundarySource: 'OpenStreetMap',
    boundarySourceDescription: 'OpenStreetMap high-resolution geometry (OSM Relation 17590236) resampled at 2.5m intervals and aligned to LMU replay telemetry.',
    parsedFrom: 'LMU Results XML (TrackVenue="Paul Ricard Circuit", TrackCourse="Paul Ricard - 1A-V2-Short") & Binary .Vcr Replay Stream',
    fiaGrade: 'FIA Grade 1',
    openedYear: 1970,
  },
};

export function getCircuitSpecification(
  venueOrKey?: string | null,
  course?: string | null
): CircuitSpecification {
  const resolvedKey = resolveTrackLayoutKey(venueOrKey, course) || venueOrKey || 'unknown';
  if (CIRCUIT_SPECIFICATIONS[resolvedKey]) {
    return CIRCUIT_SPECIFICATIONS[resolvedKey];
  }

  // Fallback if not found in dictionary
  const cleanName = venueOrKey || 'Circuit';
  return {
    layoutKey: resolvedKey,
    officialName: cleanName,
    layoutName: course || cleanName,
    country: 'International',
    countryCode: 'UN',
    flagEmoji: '🏁',
    city: 'Circuit Venue',
    officialLengthMeters: 0,
    officialLengthKm: 0,
    officialLengthMiles: 0,
    turnCount: 0,
    direction: 'Clockwise',
    famousCorners: [],
    boundarySource: 'Telemetry-Corridor',
    boundarySourceDescription: 'Telemetry corridor calibrated from LMU simulation files.',
    parsedFrom: 'LMU Results XML & Binary .Vcr Replays',
  };
}
