export interface CircuitSpecification {
  layoutKey: string;
  circuitId: string;
  layoutId: string;
  isDefaultLayout: boolean;
  benchmarkName: string;
  sceneDescs: string[];
  officialName: string;
  layoutName: string;
  country: string;
  countryCode: string;
  flagEmoji: string;
  city: string;
  officialLengthMeters: number;
  officialLengthKm: number;
  officialLengthMiles: number;
  turnCount: number;
  direction: 'Clockwise' | 'Counter-Clockwise';
  elevationChangeMeters?: number;
  nominalWidthM?: number;
  famousCorners: string[];
  fiaGrade?: string;
  openedYear?: number;
}

export const CIRCUIT_SPECIFICATIONS: Record<string, CircuitSpecification> = {
  monza_gp: {
    layoutKey: 'monza_gp',
    circuitId: 'monza',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Monza',
    sceneDescs: ["monzawec"],
    officialName: 'Autodromo Nazionale Monza',
    layoutName: 'Grand Prix Circuit',
    country: 'Italy',
    countryCode: 'IT',
    flagEmoji: '🇮🇹',
    city: 'Monza, Lombardy',
    officialLengthMeters: 5793,
    officialLengthKm: 5.793,
    officialLengthMiles: 3.600,
    turnCount: 11,
    direction: 'Clockwise',
    elevationChangeMeters: 13,
    famousCorners: ['Variante del Rettifilo (T1-T2)', 'Curva Grande (T3)', 'Variante della Roggia (T4-T5)', 'Curve di Lesmo (T6-T7)', 'Variante Ascari (T8-T10)', 'Curva Parabolica / Alboreto (T11)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1922,
  },
  monza_curvagrande: {
    layoutKey: 'monza_curvagrande',
    circuitId: 'monza',
    layoutId: 'curvagrande',
    isDefaultLayout: false,
    benchmarkName: 'Monza (curvagrande)',
    sceneDescs: ["monzawec_grande"],
    officialName: 'Autodromo Nazionale Monza',
    layoutName: 'Curva Grande Circuit',
    country: 'Italy',
    countryCode: 'IT',
    flagEmoji: '🇮🇹',
    city: 'Monza, Lombardy',
    officialLengthMeters: 5793,
    officialLengthKm: 5.793,
    officialLengthMiles: 3.600,
    turnCount: 10,
    direction: 'Clockwise',
    elevationChangeMeters: 13,
    famousCorners: ['Direct Straight to Curva Grande (Bypasses Rettifilo)', 'Variante della Roggia', 'Lesmo 1 & 2', 'Variante Ascari', 'Curva Parabolica'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1922,
  },
  spa_gp: {
    layoutKey: 'spa_gp',
    circuitId: 'spa',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Spa',
    sceneDescs: ["spaelms","spawec","spawec_endce"],
    officialName: 'Circuit de Spa-Francorchamps',
    layoutName: 'Grand Prix Circuit',
    country: 'Belgium',
    countryCode: 'BE',
    flagEmoji: '🇧🇪',
    city: 'Stavelot / Francorchamps, Ardennes',
    officialLengthMeters: 7004,
    officialLengthKm: 7.004,
    officialLengthMiles: 4.352,
    turnCount: 20,
    direction: 'Clockwise',
    elevationChangeMeters: 102,
    famousCorners: ['La Source Hairpin (T1)', 'Eau Rouge & Raidillon (T2-T4)', 'Kemmel Straight', 'Les Combes (T5-T7)', 'Bruxelles / Rivage (T8)', 'Pouhon / Double Gauche (T10-T11)', 'Fagnes / Pif-Paf (T12-T13)', 'Blanchimont (T16-T17)', 'Bus Stop Chicane (T18-T19)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1921,
  },
  sarthe_full: {
    layoutKey: 'sarthe_full',
    circuitId: 'sarthe',
    layoutId: 'full',
    isDefaultLayout: true,
    benchmarkName: 'Circuit de la Sarthe',
    sceneDescs: ["lemanswec"],
    officialName: 'Circuit des 24 Heures du Mans',
    layoutName: 'Full 24 Hours Circuit (Circuit de la Sarthe)',
    country: 'France',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    city: 'Le Mans, Sarthe',
    officialLengthMeters: 13626,
    officialLengthKm: 13.626,
    officialLengthMiles: 8.467,
    turnCount: 38,
    direction: 'Clockwise',
    elevationChangeMeters: 38,
    famousCorners: ['Dunlop Chicane & Passerelle (T1-T3)', 'Esses de la Forêt & Tertre Rouge (T4-T6)', 'Ligne Droite des Hunaudières (Mulsanne Straight)', 'Chicanes Forza & Michelin (T7-T12)', 'Mulsanne Corner (T13)', 'Indianapolis (T14-T15)', 'Arnage (T16)', 'Porsche Curves (T17-T23)', 'Maison Blanche & Ford Chicanes (T27-T33)'],
    fiaGrade: 'FIA Grade 2 / ACO Homologated',
    openedYear: 1923,
  },
  sarthe_mulsanne: {
    layoutKey: 'sarthe_mulsanne',
    circuitId: 'sarthe',
    layoutId: 'straight',
    isDefaultLayout: false,
    benchmarkName: 'Circuit de la Sarthe (straight)',
    sceneDescs: ["lemanswec_mulsanne"],
    officialName: 'Circuit des 24 Heures du Mans',
    layoutName: 'Mulsanne Circuit (without chicanes)',
    country: 'France',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    city: 'Le Mans, Sarthe',
    officialLengthMeters: 13626,
    officialLengthKm: 13.626,
    officialLengthMiles: 8.467,
    turnCount: 32,
    direction: 'Clockwise',
    elevationChangeMeters: 38,
    famousCorners: ['Dunlop Chicane', 'Tertre Rouge', 'Full 6km Unbroken Mulsanne Straight (330+ km/h)', 'Mulsanne Corner', 'Indianapolis', 'Arnage', 'Porsche Curves'],
    fiaGrade: 'FIA Grade 2 / ACO Homologated',
    openedYear: 1923,
  },
  cota_gp: {
    layoutKey: 'cota_gp',
    circuitId: 'cota',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'COTA',
    sceneDescs: ["cotawec"],
    officialName: 'Circuit of the Americas (COTA)',
    layoutName: 'Grand Prix Circuit',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Austin, Texas',
    officialLengthMeters: 5513,
    officialLengthKm: 5.513,
    officialLengthMiles: 3.426,
    turnCount: 20,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 30,
    famousCorners: ['133-ft Elevation Uphill Blind Apex (T1)', 'Maggotts/Becketts-style Esses (T2-T6)', 'Blind Sweeper (T10)', 'Hairpin (T11)', 'Multi-apex Carousel (T16-T18)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 2012,
  },
  cota_national: {
    layoutKey: 'cota_national',
    circuitId: 'cota',
    layoutId: 'national',
    isDefaultLayout: false,
    benchmarkName: 'COTA (national)',
    sceneDescs: ["cotawec_national"],
    officialName: 'Circuit of the Americas (COTA)',
    layoutName: 'National Circuit',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Austin, Texas',
    officialLengthMeters: 3702,
    officialLengthKm: 3.702,
    officialLengthMiles: 2.300,
    turnCount: 17,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 31,
    famousCorners: ['Turn 1 Uphill Apex', 'Esses Bypass Connector', 'Carousel Section'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 2012,
  },
  barcelona_gp: {
    layoutKey: 'barcelona_gp',
    circuitId: 'barcelona',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Barcelona',
    sceneDescs: ["barcelonaelms"],
    officialName: 'Circuit de Barcelona-Catalunya',
    layoutName: 'Grand Prix Circuit (Modern Layout)',
    country: 'Spain',
    countryCode: 'ES',
    flagEmoji: '🇪🇸',
    city: 'Montmeló, Catalonia',
    officialLengthMeters: 4657,
    officialLengthKm: 4.657,
    officialLengthMiles: 2.894,
    turnCount: 14,
    direction: 'Clockwise',
    elevationChangeMeters: 30,
    famousCorners: ['Elf Chicane (T1-T2)', 'Curva Renault (T3)', 'Repsol (T4)', 'Seat Hairpin (T5)', 'Campsa (T9)', 'La Caixa Hairpin (T10)', 'Fast Sweeping Final Turns (T13-T14)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1991,
  },
  interlagos_gp: {
    layoutKey: 'interlagos_gp',
    circuitId: 'interlagos',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Interlagos',
    sceneDescs: ["interlagoswec"],
    officialName: 'Autódromo José Carlos Pace (Interlagos)',
    layoutName: 'Grand Prix Circuit',
    country: 'Brazil',
    countryCode: 'BR',
    flagEmoji: '🇧🇷',
    city: 'São Paulo',
    officialLengthMeters: 4309,
    officialLengthKm: 4.309,
    officialLengthMiles: 2.677,
    turnCount: 15,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 44,
    famousCorners: ['Senna ‘S’ (T1-T2)', 'Curva do Sol (T3)', 'Descida do Lago (T4-T5)', 'Ferradura (T6-T7)', 'Laranjinha (T8)', 'Bico de Pato (T10)', 'Mergulho (T11)', 'Junção (T12)', 'Subida dos Boxes (T13-T15)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1940,
  },
  silverstone_wec: {
    layoutKey: 'silverstone_wec',
    circuitId: 'silverstone',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Silverstone (GP)',
    sceneDescs: ["silverstonewec","silverstoneelms"],
    officialName: 'Silverstone Circuit',
    layoutName: 'Grand Prix Circuit - WEC',
    country: 'United Kingdom',
    countryCode: 'GB',
    flagEmoji: '🇬🇧',
    city: 'Northamptonshire / Buckinghamshire',
    officialLengthMeters: 5890,
    officialLengthKm: 5.890,
    officialLengthMiles: 3.660,
    turnCount: 18,
    direction: 'Clockwise',
    elevationChangeMeters: 11,
    famousCorners: ['Abbey (T1)', 'Farm (T2)', 'Village & The Loop (T3-T4)', 'Brooklands (T6)', 'Luffield & Woodcote (T7-T8)', 'Copse (T9)', 'Maggotts, Becketts & Chapel (T10-T14)', 'Hangar Straight', 'Stowe (T15)', 'Vale & Club (T16-T18)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1948,
  },
  silverstone_national: {
    layoutKey: 'silverstone_national',
    circuitId: 'silverstone',
    layoutId: 'national',
    isDefaultLayout: false,
    benchmarkName: 'Silverstone (National)',
    sceneDescs: ["silverstone_national"],
    officialName: 'Silverstone Circuit',
    layoutName: 'National Circuit',
    country: 'United Kingdom',
    countryCode: 'GB',
    flagEmoji: '🇬🇧',
    city: 'Northamptonshire / Buckinghamshire',
    officialLengthMeters: 2639,
    officialLengthKm: 2.639,
    officialLengthMiles: 1.640,
    turnCount: 6,
    direction: 'Clockwise',
    elevationChangeMeters: 6,
    famousCorners: ['Copse (T1)', 'Maggotts (T2)', 'Wellington Straight Bypass', 'Brooklands', 'Luffield', 'Woodcote'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1948,
  },
  silverstone_international: {
    layoutKey: 'silverstone_international',
    circuitId: 'silverstone',
    layoutId: 'international',
    isDefaultLayout: false,
    benchmarkName: 'Silverstone (International)',
    sceneDescs: ["silverstone_international"],
    officialName: 'Silverstone Circuit',
    layoutName: 'International Circuit',
    country: 'United Kingdom',
    countryCode: 'GB',
    flagEmoji: '🇬🇧',
    city: 'Northamptonshire / Buckinghamshire',
    officialLengthMeters: 2979,
    officialLengthKm: 2.979,
    officialLengthMiles: 1.851,
    turnCount: 10,
    direction: 'Clockwise',
    elevationChangeMeters: 11,
    famousCorners: ['Abbey', 'Farm', 'The Loop', 'Hangar Straight Shortcut', 'Stowe', 'Vale', 'Club'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1948,
  },
  bahrain_wec: {
    layoutKey: 'bahrain_wec',
    circuitId: 'bahrain',
    layoutId: 'wec',
    isDefaultLayout: true,
    benchmarkName: 'Bahrain (wec)',
    sceneDescs: ["bahrainwec"],
    officialName: 'Bahrain International Circuit',
    layoutName: 'Grand Prix Circuit (WEC 8 Hours)',
    country: 'Bahrain',
    countryCode: 'BH',
    flagEmoji: '🇧🇭',
    city: 'Sakhir, Southern Governorate',
    officialLengthMeters: 5412,
    officialLengthKm: 5.412,
    officialLengthMiles: 3.363,
    turnCount: 15,
    direction: 'Clockwise',
    elevationChangeMeters: 17,
    famousCorners: ['Michael Schumacher Turn (T1-T3)', 'Oasis Turn (T4)', 'High-speed Esses (T5-T7)', 'Downhill Off-camber Hairpin (T8-T10)', 'Double Apex (T14-T15)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  bahrain_outer: {
    layoutKey: 'bahrain_outer',
    circuitId: 'bahrain',
    layoutId: 'outer',
    isDefaultLayout: false,
    benchmarkName: 'Bahrain (outer)',
    sceneDescs: ["bahrainwec_outer"],
    officialName: 'Bahrain International Circuit',
    layoutName: 'Outer Circuit',
    country: 'Bahrain',
    countryCode: 'BH',
    flagEmoji: '🇧🇭',
    city: 'Sakhir, Southern Governorate',
    officialLengthMeters: 3543,
    officialLengthKm: 3.543,
    officialLengthMiles: 2.201,
    turnCount: 11,
    direction: 'Clockwise',
    elevationChangeMeters: 19,
    famousCorners: ['T1-T3 Complex', 'Outer Link High-speed Sweepers (T4-T8)', 'Double Apex Final Turns (T10-T11)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  bahrain_paddock: {
    layoutKey: 'bahrain_paddock',
    circuitId: 'bahrain',
    layoutId: 'paddock',
    isDefaultLayout: false,
    benchmarkName: 'Bahrain (paddock)',
    sceneDescs: ["bahrainwec_paddock"],
    officialName: 'Bahrain International Circuit',
    layoutName: 'Paddock Circuit',
    country: 'Bahrain',
    countryCode: 'BH',
    flagEmoji: '🇧🇭',
    city: 'Sakhir, Southern Governorate',
    officialLengthMeters: 3705,
    officialLengthKm: 3.705,
    officialLengthMiles: 2.302,
    turnCount: 10,
    direction: 'Clockwise',
    elevationChangeMeters: 16,
    famousCorners: ['Paddock Straight Bypass', 'Inner Infield Complex', 'Technical Hairpin Sections'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  bahrain_endurance: {
    layoutKey: 'bahrain_endurance',
    circuitId: 'bahrain',
    layoutId: 'endurance',
    isDefaultLayout: false,
    benchmarkName: 'Bahrain (endurance)',
    sceneDescs: ["bahrainwec_endce"],
    officialName: 'Bahrain International Circuit',
    layoutName: 'Endurance Circuit',
    country: 'Bahrain',
    countryCode: 'BH',
    flagEmoji: '🇧🇭',
    city: 'Sakhir, Southern Governorate',
    officialLengthMeters: 6299,
    officialLengthKm: 6.299,
    officialLengthMiles: 3.914,
    turnCount: 24,
    direction: 'Clockwise',
    elevationChangeMeters: 19,
    famousCorners: ['T1-T3 Complex', 'Extended Infield Loop (T4-T13)', 'High-speed Sweepers', 'Double Apex (T23-T24)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  imola_gp: {
    layoutKey: 'imola_gp',
    circuitId: 'imola',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Imola',
    sceneDescs: ["imolaelms","imolawec"],
    officialName: 'Autodromo Internazionale Enzo e Dino Ferrari',
    layoutName: 'Grand Prix Circuit (Imola)',
    country: 'Italy',
    countryCode: 'IT',
    flagEmoji: '🇮🇹',
    city: 'Imola, Emilia-Romagna',
    officialLengthMeters: 4909,
    officialLengthKm: 4.909,
    officialLengthMiles: 3.050,
    turnCount: 20,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 34,
    famousCorners: ['Variante Tamburello (T2-T4)', 'Variante Villeneuve (T5-T6)', 'Tosa Hairpin (T7)', 'Piratella (T9)', 'Acque Minerali (T11-T13)', 'Variante Alta (T14-T15)', 'Rivazza 1 & 2 (T17-T18)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1953,
  },
  daytona_road_course: {
    layoutKey: 'daytona_road_course',
    circuitId: 'daytona',
    layoutId: 'road',
    isDefaultLayout: true,
    benchmarkName: 'Daytona',
    sceneDescs: ["daytonarc"],
    officialName: 'Daytona International Speedway',
    layoutName: 'Road Course (with Le Mans Chicane)',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Daytona Beach, Florida',
    officialLengthMeters: 5729,
    officialLengthKm: 5.729,
    officialLengthMiles: 3.560,
    turnCount: 13,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 4,
    famousCorners: ['Infield Horseshoe (T1)', 'International Horseshoe (T3)', 'Kink (T4)', 'West Hairpin (T5-T6)', '31° High-banked Oval Turns (T7 & T13)', 'Backstretch Le Mans "Bus Stop" Chicane (T8-T11)'],
    fiaGrade: 'FIA Grade 2 / IMSA Homologated',
    openedYear: 1959,
  },
  fuji_chicane: {
    layoutKey: 'fuji_chicane',
    circuitId: 'fuji',
    layoutId: 'chicane',
    isDefaultLayout: true,
    benchmarkName: 'Fuji (chicane)',
    sceneDescs: ["fujiwec"],
    officialName: 'Fuji Speedway',
    layoutName: 'Grand Prix Circuit (with Dunlop Chicane)',
    country: 'Japan',
    countryCode: 'JP',
    flagEmoji: '🇯🇵',
    city: 'Oyama, Shizuoka Prefecture',
    officialLengthMeters: 4563,
    officialLengthKm: 4.563,
    officialLengthMiles: 2.835,
    turnCount: 16,
    direction: 'Clockwise',
    elevationChangeMeters: 37,
    famousCorners: ['1.475 km Main Straight', 'T1 Daiichi (First Corner Hairpin)', 'Coca-Cola Corner (T3)', '100R (T4-T5)', 'Hairpin Corner (T6)', 'Dunlop Chicane (T10-T12)', '13th Corner', 'GR Supra / Netz Corner (T15)', 'Panasonic Corner (T16)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1965,
  },
  fuji_classic: {
    layoutKey: 'fuji_classic',
    circuitId: 'fuji',
    layoutId: 'classic',
    isDefaultLayout: false,
    benchmarkName: 'Fuji (classic)',
    sceneDescs: ["fujiwec_cl"],
    officialName: 'Fuji Speedway',
    layoutName: 'Classic Circuit (without Dunlop Chicane)',
    country: 'Japan',
    countryCode: 'JP',
    flagEmoji: '🇯🇵',
    city: 'Oyama, Shizuoka Prefecture',
    officialLengthMeters: 4526,
    officialLengthKm: 4.526,
    officialLengthMiles: 2.812,
    turnCount: 14,
    direction: 'Clockwise',
    elevationChangeMeters: 37,
    famousCorners: ['Main Straight', 'First Corner', '100R', 'Hairpin', 'Dunlop Bypass Straight', '13th Corner', 'Netz Corner', 'Panasonic Corner'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1965,
  },
  portimao_wec: {
    layoutKey: 'portimao_wec',
    circuitId: 'portimao',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Portimao',
    sceneDescs: ["portimaoelms","portimaowec"],
    officialName: 'Autódromo Internacional do Algarve (Portimão)',
    layoutName: 'Grand Prix Circuit - WEC',
    country: 'Portugal',
    countryCode: 'PT',
    flagEmoji: '🇵🇹',
    city: 'Portimão, Algarve',
    officialLengthMeters: 4653,
    officialLengthKm: 4.653,
    officialLengthMiles: 2.891,
    turnCount: 15,
    direction: 'Clockwise',
    elevationChangeMeters: 28,
    famousCorners: ['Primeira (T1)', 'Lagos (T3)', 'Hairpin (T5)', 'Portimão Blind Crest (T8)', 'Craig Jones (T9)', 'Torre VIP Hairpin (T10-T11)', 'Galp (T14)', 'Curvão Blind Downhill Rollercoaster Drop (T15)'],
    nominalWidthM: 14.0,
    fiaGrade: 'FIA Grade 1',
    openedYear: 2008,
  },
  sebring_full: {
    layoutKey: 'sebring_full',
    circuitId: 'sebring',
    layoutId: 'full',
    isDefaultLayout: true,
    benchmarkName: 'Sebring',
    sceneDescs: ["sebringwec"],
    officialName: 'Sebring International Raceway',
    layoutName: 'Full 12-Hour Circuit',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Sebring, Florida',
    officialLengthMeters: 6019,
    officialLengthKm: 6.019,
    officialLengthMiles: 3.740,
    turnCount: 17,
    direction: 'Clockwise',
    elevationChangeMeters: 3,
    famousCorners: ['Rough Concrete Bumps Turn 1 (T1)', 'Apex Hairpin (T3)', 'Hairpin (T7)', 'Fangio Bends (T8)', 'Cunningham (T10)', 'Collier (T11)', 'Tower Turn (T13)', 'Le Mans / Ulmann Straight', 'Sunset Bend Bumpy Concrete Carousel (T17)'],
    fiaGrade: 'FIA Grade 2 / IMSA Homologated',
    openedYear: 1950,
  },
  sebring_school: {
    layoutKey: 'sebring_school',
    circuitId: 'sebring',
    layoutId: 'school',
    isDefaultLayout: false,
    benchmarkName: 'Sebring (school)',
    sceneDescs: ["sebringwec_school"],
    officialName: 'Sebring International Raceway',
    layoutName: 'School Circuit (Short Layout)',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Sebring, Florida',
    officialLengthMeters: 3219,
    officialLengthKm: 3.219,
    officialLengthMiles: 2.000,
    turnCount: 7,
    direction: 'Clockwise',
    elevationChangeMeters: 2,
    famousCorners: ['Turn 1 Concrete', 'Hairpin Section', 'Runway Paddock Connector', 'Sunset Bend'],
    fiaGrade: 'FIA Grade 2',
    openedYear: 1950,
  },
  laguna_seca: {
    layoutKey: 'laguna_seca',
    circuitId: 'laguna_seca',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Laguna Seca',
    sceneDescs: ["lagunaseca"],
    officialName: 'WeatherTech Raceway Laguna Seca',
    layoutName: 'Grand Prix Circuit',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Monterey County, California',
    officialLengthMeters: 3602,
    officialLengthKm: 3.602,
    officialLengthMiles: 2.238,
    turnCount: 11,
    direction: 'Counter-Clockwise',
    elevationChangeMeters: 55,
    famousCorners: ['Andretti Hairpin (T2)', 'Rahal Straight', 'The Corkscrew 5.5-story Blind Plunge (T8-T8A)', 'Rainey Curve (T9)', 'Final Hairpin (T11)'],
    fiaGrade: 'FIA Grade 2 / IMSA Homologated',
    openedYear: 1957,
  },
  qatar_short: {
    layoutKey: 'qatar_short',
    circuitId: 'qatar',
    layoutId: 'short',
    isDefaultLayout: false,
    benchmarkName: 'Qatar (short)',
    sceneDescs: ["qatarwec_short"],
    officialName: 'Lusail International Circuit',
    layoutName: 'Short Circuit',
    country: 'Qatar',
    countryCode: 'QA',
    flagEmoji: '🇶🇦',
    city: 'Lusail, Al Daayen',
    officialLengthMeters: 3701,
    officialLengthKm: 3.701,
    officialLengthMiles: 2.300,
    turnCount: 11,
    direction: 'Clockwise',
    elevationChangeMeters: 4,
    famousCorners: ['Main Straight', 'Turn 1 Hairpin', 'Inner Short Infield Link', 'High-speed Final Complex'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  qatar_gp: {
    layoutKey: 'qatar_gp',
    circuitId: 'qatar',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Qatar',
    sceneDescs: ["qatarwec"],
    officialName: 'Lusail International Circuit',
    layoutName: 'Grand Prix Circuit (Qatar 1812KM)',
    country: 'Qatar',
    countryCode: 'QA',
    flagEmoji: '🇶🇦',
    city: 'Lusail, Al Daayen',
    officialLengthMeters: 5400,
    officialLengthKm: 5.400,
    officialLengthMiles: 3.355,
    turnCount: 16,
    direction: 'Clockwise',
    elevationChangeMeters: 4,
    famousCorners: ['1.068 km Main Straight', 'Turn 1 Hard Braking', 'Triple-Apex High-G Complex (T12-T14)', 'Turn 16 Final Sweeper'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 2004,
  },
  paul_ricard_1a_v2_short: {
    layoutKey: 'paul_ricard_1a_v2_short',
    circuitId: 'paul_ricard',
    layoutId: '1a_v2_short',
    isDefaultLayout: false,
    benchmarkName: 'Paul Ricard (1A v2 short)',
    sceneDescs: ["paulricard1a-v2-short"],
    officialName: 'Circuit Paul Ricard',
    layoutName: '1A-V2 Short Circuit',
    country: 'France',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    city: 'Le Castellet, Var',
    officialLengthMeters: 5227,
    officialLengthKm: 5.227,
    officialLengthMiles: 3.248,
    turnCount: 14,
    direction: 'Clockwise',
    elevationChangeMeters: 30,
    famousCorners: ['S de la Verrerie (T1-T2)', 'Sainte-Baume (T3-T5)', 'Ligne Droite du Mistral with Chicane (T6-T9)', 'Courbe de Signes 290+ km/h Flat-out Sweeper (T10)', 'Double Droite du Beausset (T11-T12)', 'Bendor (T13)', 'Pont (T14)'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1970,
  },
  paul_ricard_1a_v2: {
    layoutKey: 'paul_ricard_1a_v2',
    circuitId: 'paul_ricard',
    layoutId: '1a_v2',
    isDefaultLayout: true,
    benchmarkName: 'Paul Ricard (1A v2)',
    sceneDescs: ["paulricard1a-v2","paulricardelms"],
    officialName: 'Circuit Paul Ricard',
    layoutName: '1A-V2 Circuit (with Mistral Chicane)',
    country: 'France',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    city: 'Le Castellet, Var',
    officialLengthMeters: 5842,
    officialLengthKm: 5.842,
    officialLengthMiles: 3.630,
    turnCount: 15,
    direction: 'Clockwise',
    elevationChangeMeters: 30,
    famousCorners: ['S de la Verrerie', 'Chicane Nord', 'Courbe de Signes', 'Le Beausset'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1970,
  },
  paul_ricard_1a: {
    layoutKey: 'paul_ricard_1a',
    circuitId: 'paul_ricard',
    layoutId: '1a',
    isDefaultLayout: false,
    benchmarkName: 'Paul Ricard (1A)',
    sceneDescs: ["paulricard1a"],
    officialName: 'Circuit Paul Ricard',
    layoutName: '1A Circuit (without Mistral Chicane)',
    country: 'France',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    city: 'Le Castellet, Var',
    officialLengthMeters: 5752,
    officialLengthKm: 5.752,
    officialLengthMiles: 3.574,
    turnCount: 13,
    direction: 'Clockwise',
    elevationChangeMeters: 30,
    famousCorners: ['S de la Verrerie', 'Mistral 1.8km Full Straight (330+ km/h)', 'Courbe de Signes Flat-out', 'Le Beausset'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1970,
  },
  paul_ricard_3a: {
    layoutKey: 'paul_ricard_3a',
    circuitId: 'paul_ricard',
    layoutId: '3a',
    isDefaultLayout: false,
    benchmarkName: 'Paul Ricard (3A)',
    sceneDescs: ["paulricard3a"],
    officialName: 'Circuit Paul Ricard',
    layoutName: '3A Short Circuit',
    country: 'France',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    city: 'Le Castellet, Var',
    officialLengthMeters: 3793,
    officialLengthKm: 3.793,
    officialLengthMiles: 2.357,
    turnCount: 13,
    direction: 'Clockwise',
    elevationChangeMeters: 20,
    famousCorners: ['Short Infield Chicane', 'North Loop', 'Le Beausset'],
    fiaGrade: 'FIA Grade 1',
    openedYear: 1970,
  },
  long_beach: {
    layoutKey: 'long_beach',
    circuitId: 'long_beach',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Long Beach',
    sceneDescs: ["longbeach"],
    officialName: 'Grand Prix of Long Beach',
    layoutName: 'Street Circuit',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Long Beach, California',
    officialLengthMeters: 3167,
    officialLengthKm: 3.167,
    officialLengthMiles: 1.968,
    turnCount: 11,
    direction: 'Clockwise',
    elevationChangeMeters: 3,
    famousCorners: ['Shoreline Drive Straight', 'Turn 1 Left Sweeper', 'Fountain Section (T2-T3)', 'Pine Avenue (T6)', 'Seaside Way', 'Turn 11 Tight Hairpin'],
    fiaGrade: 'FIA Grade 2 / IMSA Homologated',
    openedYear: 1975,
  },
  road_atlanta: {
    layoutKey: 'road_atlanta',
    circuitId: 'road_atlanta',
    layoutId: 'gp',
    isDefaultLayout: true,
    benchmarkName: 'Road Atlanta',
    sceneDescs: ["roadatlanta"],
    officialName: 'Michelin Raceway Road Atlanta',
    layoutName: 'Grand Prix Circuit',
    country: 'United States',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    city: 'Braselton, Georgia',
    officialLengthMeters: 4088,
    officialLengthKm: 4.088,
    officialLengthMiles: 2.540,
    turnCount: 12,
    direction: 'Clockwise',
    elevationChangeMeters: 38,
    famousCorners: ['Turn 1 Uphill Blind Crest', 'The Esses (T2-T4)', 'Turn 5 Uphill Left', 'Turn 7 Leading to Long Backstraight', 'Turn 10A-10B Downhill Chicane', 'Turn 12 Under the Bridge Blind Plunge'],
    fiaGrade: 'FIA Grade 2 / IMSA Homologated',
    openedYear: 1970,
  },
};

/**
 * Derived lookup table mapping all known LMU internal sceneDesc codes (in lowercase)
 * directly to repository layoutKeys without duplicate maintenance.
 */
export const LMU_SCENE_DESC_MAP: Record<string, string> = Object.fromEntries(
  Object.values(CIRCUIT_SPECIFICATIONS).flatMap(spec =>
    spec.sceneDescs.map(desc => [desc.toLowerCase(), spec.layoutKey])
  )
);
