/**
 * Rebuilds shared/domain/vehicleCatalog.ts from LMU results logs.
 *
 * Every <Driver> in a results XML names its vehicle file (<VehFile>, the same id the replay
 * roster stores) next to the car it is (<CarType>) and its class (<CarClass>). A vehicle file is
 * one livery of one car, so the pairing is exact, whereas team tokens inside the id are not: DKR,
 * WRT, PROT, IRON, AFCO or UNIT each run cars in several classes. Entries already in the catalog
 * are kept, because LMU deletes old logs.
 *
 * Usage: npm run vehicles:catalog -- [resultsDir]
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { VEHICLE_FILE_GROUPS } from '../../shared/domain/vehicleCatalog.js';
import { normalizeLmuCarClass, normalizeLmuCarType } from '../../shared/domain/vehicleMapping.js';

const DEFAULT_RESULTS_DIR = 'C:/Program Files (x86)/Steam/steamapps/common/Le Mans Ultimate/UserData/Log/Results';
const OUTPUT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../shared/domain/vehicleCatalog.ts');

function readTag(block: string, tag: string): string {
  const match = block.match(new RegExp(`<${tag}>([^<]*)</${tag}>`));
  return match ? match[1].trim() : '';
}

function collect(resultsDir: string): Map<string, { model: string; carClass: string }> {
  const byId = new Map<string, { model: string; carClass: string }>();
  for (const group of VEHICLE_FILE_GROUPS) {
    for (const id of group.vehicleIds) byId.set(id, { model: group.model, carClass: group.carClass });
  }
  const files = fs.readdirSync(resultsDir).filter(name => name.toLowerCase().endsWith('.xml'));
  for (const file of files) {
    const xml = fs.readFileSync(path.join(resultsDir, file), 'utf8');
    for (const block of xml.split('<Driver>').slice(1)) {
      const id = readTag(block, 'VehFile').replace(/\.veh$/i, '').toUpperCase();
      const carType = readTag(block, 'CarType');
      const carClass = readTag(block, 'CarClass');
      if (!id || !carType || !carClass) continue;
      const entry = { model: normalizeLmuCarType(carType), carClass: normalizeLmuCarClass(carClass) };
      const known = byId.get(id);
      if (known && (known.model !== entry.model || known.carClass !== entry.carClass)) {
        console.warn(`${id}: ${known.model}/${known.carClass} in the catalog, ${entry.model}/${entry.carClass} in ${file}`);
        continue;
      }
      byId.set(id, entry);
    }
  }
  console.log(`${files.length} logs, ${byId.size} vehicle files`);
  return byId;
}

function render(byId: Map<string, { model: string; carClass: string }>): string {
  const groups = new Map<string, { model: string; carClass: string; ids: string[] }>();
  for (const [id, entry] of byId) {
    const key = `${entry.carClass}\u0000${entry.model}`;
    const group = groups.get(key) ?? { ...entry, ids: [] };
    group.ids.push(id);
    groups.set(key, group);
  }
  const sorted = [...groups.values()].sort((a, b) => a.carClass.localeCompare(b.carClass) || a.model.localeCompare(b.model));
  const lines = [
    '// Generated by tools/analysis/buildVehicleCatalog.ts from LMU results logs, where each',
    '// <VehFile> (the vehicle id a replay roster stores) is listed with its <CarType> and <CarClass>.',
    '// Regenerate rather than edit by hand; ids missing here fall back to the rules in vehicleMapping.ts.',
    '',
    'export interface VehicleFileGroup {',
    '  model: string;',
    '  carClass: string;',
    '  vehicleIds: readonly string[];',
    '}',
    '',
    'export const VEHICLE_FILE_GROUPS: readonly VehicleFileGroup[] = [',
  ];
  for (const group of sorted) {
    lines.push(`  { model: '${group.model}', carClass: '${group.carClass}', vehicleIds: [`);
    const ids = group.ids.sort().map(id => `'${id}'`);
    for (let i = 0; i < ids.length; i += 4) lines.push(`    ${ids.slice(i, i + 4).join(', ')},`);
    lines.push('  ] },');
  }
  lines.push('];', '');
  return lines.join('\n');
}

const resultsDir = process.argv[2] || DEFAULT_RESULTS_DIR;
fs.writeFileSync(OUTPUT, render(collect(resultsDir)));
console.log(`Wrote ${path.relative(process.cwd(), OUTPUT)}`);
